services:
  db:
    image: postgres:15-alpine
    container_name: vacancy_db
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super_secret_password}
      POSTGRES_DB: ${POSTGRES_DB:-adp_db}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  

  redis:
    image: redis:7-alpine
    container_name: vacancy_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    build: .
    container_name: vacancy_app
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data: